#ifndef THREE_ADDR_CODE_H
#define THREE_ADDR_CODE_H

#include "ast.h"
#include <fstream>
#include <string>
#include <map>

using namespace std;

class ThreeAddrCodeGenerator {
private:
    ProgramNode* ast_root;
    ofstream& outcode;
    map<string, string> symbol_to_temp;
    int temp_count;
    int label_count;

public:
    ThreeAddrCodeGenerator(ProgramNode* root, ofstream& out)
        : ast_root(root), outcode(out), temp_count(0), label_count(0) {}

    void generate() {
        // TODO: Implement this method
        // This method should:
        // 1. Write a header to the output file
        // 2. Call the generate_code method of the AST root
        // 3. Write a footer to the output file
        outcode << "//========= Three Address Code Start =========" << endl;
        outcode << "// This code was generated by a two pass compiler" << endl;
        outcode << "// Format: " << endl;
        outcode << "// - to, t1, etc. are temporarry variables" << endl;
        outcode << "// - L0, l1. etc. are labels for jumps" << endl;
        outcode << "// - operations follo the three address code format" << endl;
        outcode << "// Three Address Code" << endl << endl;

        if (ast_root){
            ast_root->generate_code(outcode, symbol_to_temp, temp_count, label_count);
        }
        outcode << endl << "//========= END OF CODE =========" << endl << endl;
    }

    // You may add helper methods here
};

#endif // THREE_ADDR_CODE_H